# -*- coding: utf-8 -*-
"""Image to Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZXUueXciwjkOAWLHpyf1Hlh1NW66Uvu

# Image to Text using CV2 and Pytesseract
"""

!pip install pytesseract
!sudo apt-get install tesseract-ocr
from google.colab.patches import cv2_imshow
import cv2
from PIL import Image
import pytesseract

# Load the image using OpenCV
img = cv2.imread('atomichabits.jpg')

# Convert the image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Use Pytesseract to perform OCR on the grayscale image
text = pytesseract.image_to_string(gray)

"""Displaying original Image"""

resized_img = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))
cv2_imshow(resized_img)

"""Converting to Text"""

print(text)